dag_id: raw_mpx_chapters_delta
start_date: 2020-07-01T00:00:00
schedule: "0 5 * * *"
pipeline:
  upstream_check:
    - name: s3_mpx_chapters
      type: s3_sensor
      on_fail:
        - sns_alarm
      retries: 4
      retry_delay: 3600
      depends_on_past: false
      s3_key:
        timeout: 120
        poke_interval: 60
        wildcard_match: True
        bucket_name: "{run_env}-raw-vip-aetnd-com"
        bucket_key: "aetn/mpx_media/%Y-%m-%d/*.json"
        time_aware_bucket_key: true
#    - name: upstream_file_check
#      job_type: QA
#      type: databricks
#      run_missing_dates: "no"
#      retries: 4
#      retry_delay: 3600
#      on_fail:
#        - sns_alarm
#      on_success:
#      max_retry: 1
#      job_params:
#        source_name: mpx_media
#      depends_on:
#        - s3_mpx_chapters
  etl:
    - name: etl_raw_mpx_chapters
      job_name: raw_mpx_chapters_delta
      job_type: ETL
      type: databricks
      run_missing_dates: "no"
      on_fail:
        - sns_alarm
      on_success:
      retries: 3
      retry_delay: 3600
      job_params:
        source_name: mpx_media
      depends_on:
        - s3_mpx_chapters
