dag_id: raw_aetn_ua_users
start_date: 2018-11-01T00:00:00
schedule: "0 5 * * *"
pipeline:
  upstream_check:
    - name: s3_aetn_ua_users
      type: s3_sensor
      on_fail:
        - sns_alarm
      retries: 4
      retry_delay: 3600
      depends_on_past: false
      s3_key:
        timeout: 120
        poke_interval: 60
        wildcard_match: True
        bucket_name: "{run_env}-raw-vip-aetnd-com"
        bucket_key: "aetn/ua/%Y-%m-%d/users.csv"
        time_aware_bucket_key: true
    - name: upstream_file_check
      job_type: QA
      type: databricks
      run_missing_dates: "no"
      retries: 4
      retry_delay: 3600
      on_fail:
        - sns_alarm
      on_success:
      max_retry: 1
      job_params:
        source_name: ua
      depends_on:
        - s3_aetn_ua_users
  pre_dqa:
    - name: pre_dqa_raw_aetn_ua_users
      job_name: raw_aetn_ua_users
      job_type: PRE_DQA
      type: databricks
      run_missing_dates: "no"
      on_fail:
        - sns_alarm
      on_success:
      retries: 3
      retry_delay: 3600
      job_params:
        source_name: ua
      depends_on:
        - upstream_file_check
  etl:
    - name: etl_raw_aetn_ua_users
      job_name: raw_aetn_ua_users
      job_type: ETL
      type: databricks
      on_fail:
        - sns_alarm
      on_success:
      retries: 3
      retry_delay: 3600
      job_params:
        source_name: ua
      depends_on:
        - upstream_file_check
