dag_id: stage_profile_to_agility_delta
start_date: 2020-07-01T00:00:00
schedule: "45 7 * * *"
pipeline:
#  raw:
#    - name: ext_raw_gigya_sso
#      type: external_task_sensor
#      run_missing_dates: "no"
#      external_dag_id:  raw_gigya_sso
#      external_task_id: etl_raw_gigya_sso
#      on_fail:
#        - sns_alarm
#    - name: ext_raw_aetn_ua_users_ac_individual
#      type: external_task_sensor
#      run_missing_dates: "no"
#      external_dag_id:  raw_aetn_ua_users_delta
#      external_task_id: etl_raw_aetn_ua_users
#      on_fail:
#        - sns_alarm
#    - name: ext_raw_email_recipient_ac_individual
#      type: external_task_sensor
#      run_missing_dates: "no"
#      external_dag_id:  raw_email_recipient
#      external_task_id: etl_raw_email_recipient
#      on_fail:
#        - sns_alarm
#    - name: ext_raw_marketing_ua_users_ac_individual
#      type: external_task_sensor
#      run_missing_dates: "no"
#      external_dag_id:  raw_marketing_ua_users
#      external_task_id: etl_raw_marketing_ua_users
#      on_fail:
#        - sns_alarm
  stage:
    - name: stage_profile_to_agility_delta
      type: databricks
      job_type: STAGE
      run_missing_dates: "no"
      on_fail:
        - sns_alarm
      retries: 3
      retry_delay: 3600
      trigger_rule: all_done
      depends_on_past: true
#      depends_on:
#        - ext_raw_gigya_sso
#        - ext_raw_aetn_ua_users_ac_individual
#        - ext_raw_email_recipient_ac_individual
#        - ext_raw_marketing_ua_users_ac_individual
